[#csharp2]
= C# alapok II.

== Előkészítés

Első lépésként hozzunk létre egy .NET Core C# konzolalkalmazást: File → New → Project... → Installed → Templates → Visual C# → .NET Core → Console Application (.NET Core). A neve legyen _HelloCSharp2_, itt ismét említsük meg a .NET konvenciókat az elnevezésre: PascalCasing típusneveknél/névtereknél/metódusoknál, camelCasing lokális és privát változók esetén. A betűszavakat is 3 betű felett (egyre gyakoribb, hogy már 2 betű esetén is) nem kapitális betűkkel, hanem PascalCasinget használva írjuk. A solutiont ne tegyük külön mappába (_Create directory for solution_ elem legyen üresen hagyva).

Próbáljuk ki a generált projektet mindenféle változtatás nélkül. Nézzünk bele a kimeneti könyvtárba: látható, hogy az alkalmazásunkból a fordítás során egy cross-platform bináris (.dll) és .NET Core v3 óta egy platform specifikus futtatható állomány (Windows esetén .exe) is generálódik. Kipróbálhatjuk, hogy az exe a szokott módon indítható (pl. duplaklikkel), míg a dll a dotnet paranccsal.

[source]
----
dotnet <projektnév.dll>
----

TIP:  A laborhoz tartozó snippet fájl: cs2.md

Adjunk a létrejövő projekthez egy `Dog` osztályt _Dog.cs_ néven, ez lesz az adatmodellünk:

TIP:  A snippet fájlból is bemásolhatjuk

[source,csharp]
----
public class Dog
{
    public string Name { get; set; }
    public Guid Id { get; } = Guid.NewGuid();
    public DateTime DateOfBirth { get; set; }
    private int AgeInDays => DateTime.Now.Subtract(DateOfBirth).Days;
    public int Age => AgeInDays / 365;
    public int AgeInDogYears => AgeInDays * 7 / 365;
    public override string ToString() =>
            $"{Name} ({Age} | {AgeInDogYears}) [ID: {Id}]";
}
----

Az adatmodell az előző órán létrehozotthoz nagyon hasonlít, ennek viszont nincsen explicit konstruktora és a `Name` és `DateOfBirth` tulajdonságok publikusan állíthatók is.

== Objektum inicializálók

Az _object initializer_ segítségével egy éppen létrehozott objektum beállítható tulajdonságait állítjuk be (a meghatározott sorrendben). Az objektum inicializáló csak konstruktorhívás esetén használható, így pl. factory metódus által gyártott objektumpéldány esetén nem. Elsődleges célja, hogy elkülönüljön az objektumon végzett művelet az inicializáló, adatfeltöltő logikától.

A Main metódusban írhatjuk az alábbi példát:

[source,csharp]
----
static void Main(string[] args)
{
    Dog banan = new Dog()
    {
            Name = "Banán",
            DateOfBirth = new DateTime(2014, 06, 10)
    };
    Console.WriteLine(banan);
    Console.ReadLine();
}
----

TIP:  Általában 1-2 tulajdonság esetén lehet egy sorba is írni az inicializációt, több esetén viszont általában több sorba érdemes tördelni az olvashatóság érdekében.

Láthatjuk, hogy csak az aktuális kontextusban egyébként is látható és beállítható tulajdonságokat állíthatjuk be, egyik így beállított tulajdonság sem kötelező jellegű. Ha az alapértelmezett konstruktort használjuk (szintén csak ha látható számunkra), akkor nem szükséges kitenni a [.light]#zárójeleket#.

[source,csharp]
----
/**/Dog banan = new Dog() {/*..*/}

    var watson = new Dog { Name = "Watson" };

/**/Console.WriteLine(banan);
/**/Console.ReadLine();
----

A `var` kulcsszó jelentősége: ha a fordító ki tudja találni a kontextusból az értékadás jobb oldalán álló érték típusát, nem szükséges a típus nevét explicit megadnunk, az implicit következik a kódból. Ebben az esetben a típus egyértelműen `Dog`. Ha csak deklarálni szeretnénk egy változót (nem adunk értékül a változónak semmit), akkor nem használhatjuk a `var` kulcsszót, ugyanis nem következik a kódból a változó típusa. Ekkor explicit meg kell adnunk a típust.

[source,csharp]
----
/**/var watson = new Dog { Name = "Watson" };

    var unnamed = new Dog { DateOfBirth = new DateTime(2017, 02, 10) };
    var unknown = new Dog { };
    //var error; <= compiler error!

    var dogs = new List<Dog>();
    dogs.Add(banan);
    dogs.Add(watson);
    dogs.Add(unnamed);
    dogs.Add(unknown);

    foreach (var dog in dogs)
        Console.WriteLine(dog);

/**/ //Console.WriteLine(banan);
/**/Console.ReadLine();
----

Az object initializer valóban csak az egyes tulajdonságokat állítja be, tehát csak szintaktikailag különbözik az első definíció az alábbitól:

[source,csharp]
----
var _banan = new Dog();
_banan.Name = "Banán";
_banan.DateOfBirth = new DateTime(2014, 06, 10);
var banan = _banan;
----

NOTE:  Elég, ha a snippet fájlból bemutatjuk, nem kell beírni

A háttérben tényleg egy (számunkra nem látható) temporális változóban fog történni az inicializáció, ugyanis, ha az object initializer kivételt dob (az egyik setter által), az objektumunk nem veszi fel a kívánt értéket.

Az object initializer hasznos lehet abban az esetben is, ha át szeretnénk adni egy paramétert egy metódusnak, de az adott objektumnak sokféle tulajdonsága lehet, így nem feltétlenül érdemes a sokparaméteres konstruktorhívásokkal pepecselni; sőt, lehetséges, hogy nem is férünk hozzá a szükséges implementációhoz.

== Using static

Ha egy osztály statikus tagjait vagy egy statikus osztályt szeretnénk használni, lehetőségünk van a `using static` kulcsszavakkal az osztályt az aktuális kontextusunkba referálni. Ha a `Console` osztályt referáljuk ilyen módon, lehetőségünk van a rajta levő metódusok meghívására az aktuális kontextusunkban:

[source,csharp]
----

/**/using System;
    using static System.Console;

/**/foreach (var dog in dogs)    
    /* Console.*/WriteLine(dog);
    /* Console.*/ReadLine();
----

TIP:  Ilyenkor a szimbólumütközések feloldására használatos általános szabályt használjuk: ha egyértelműen feloldható a hivatkozás, akkor nem szükséges kitenni a megkülönböztető előtagot (itt: osztály), különben igen.

== Nullozható típusok

Természetesen a referenciatípusok mind olyan típusok, melyek vehetnek fel null értéket, viszont esetenként jó volna, ha a `null` értéket egyébként felvenni nem képes típusok is lehetének ilyen értékűek, ezzel pl. jelezvén, hogy egy érték be van-e állítva vagy sem. Pl. egy szám esetén a 0 egy konkrét, helyes érték lehet a domain modellünkben, a `null` viszont azt jelenthetné, hogy nem vett fel értéket.

Vizsgáljuk meg, hogy a konzolra történő kiíráskor miért lesz 2018 Watson életkora! A `Console.WriteLine` parancshoz vegyünk fel egy töréspontot (F9), ezután vegyük fel a `dog.Name` és `dog.AgeInDays` kifejezést a _Watch_ ablakba! Ha _F5_-tel lépkedünk, láthatjuk, hogy Watson 2018 évesnek vélt. Amíg a program futása fel van függesztve a törésponton, vegyünk fel egy másikat az `AgeInDays` tulajdonság kiértékelésébe a `Dog` osztályban! Láthatjuk, hogy a turpisság abból fakad, hogy a `DateTime` nem referenciatípus, és alapértelmezés szerinti értéke `0001. 01. 01. 00:00:00`.

Ennek a javításához az `Age` tulajdonság típusát változtassuk `int?`-re! Az `int?` szintaktikai édesítőszere a `Nullable<int>`-nek, egy olyan struktúrának, ami egy `int` értéket tárol, és tárolja, hogy az be van-e állítva vagy sem. A `Nullable<int>` szignatúráit megmutathatjuk, hogyha a kurzort a típusra helyezve _F12_-t nyomunk.

Módosítsuk a `Dog` `Age` és `DateOfBirth` tulajdonságait, hogy tudjuk, be vannak-e állítva az értékeik:

[source,csharp]
----
public DateTime? DateOfBirth { get; set; }

private int? AgeInDays => (-DateOfBirth?.Subtract(DateTime.Now))?.Days;

public int? Age => AgeInDays / 365;

public int? AgeInDogYears => AgeInDays * 7 / 365;
----

Az `AgeInDays` akkor ad vissza `null` értéket, ha a `DateOfBirth` maga is `null` volt. Tehát ha nincs megadva születési dátumunk, nem tudunk életkort sem számítani. Ehhez magyarázzuk el a `?.` (Elvis, magyarban Kozsó - `null` conditional operator) operátor jelentését: a kiértékelendő érték jobb oldalát adja vissza, ha a bal oldal nem `null`, különben `null`-t. A kifejezést meg kellett változtatnunk, hogy a `DateOfBirth`-ből vonjuk ki a jelenlegi dátumot és ezt negáljuk, ugyanis a `null` vizsgálandó érték a bináris operátor bal oldalán kell, hogy elhelyezkedjen.

NOTE:  Az Elvis operátor nevének erdetére több magyarázatot is lehet találni, a források annyiban nagyrészt megegyeznek, hogy a kérdőjel tekeredő része az énekes jellegzetes bodorodó hajviseletére emlékeztet, a pontok pedig a szemeket jelölik, így végülis a ?. egy Elvis emotikonként fogható fel. Ezen logika mentén adódik a magyar megfelelő, a Kozsó operátor, hiszen a szem körül tekergőző legikonikusabb hajtincs a magyar zenei kultúrában Kozsó nevéhez köthető.

Ha most futtatjuk az alkalmazást, az `AgeInDays` és a származtatott tulajdonságok értéke null lesz, ha a születési dátum nincs megadva.

== Kollekció inicializálók

A kollekció inicializálók (collection initializer) egy szintaktikai édesítőszer arra az esetre, amikor kollekcióban levő elemeket a kollekció létrehozásával összevont műveletként szeretnénk kezelni.

[source,csharp]
----
var dogs = new List<Dog>();
dogs.Add(banan);
dogs.Add(watson);
dogs.Add(unnamed);
dogs.Add(unknown);
----

A fenti kódrészletet rövidebben, átláthatóbban is tudjuk kezelni az alábbi szintaxissal:

[source,csharp]
----
/*
var dogs = new List<Dog>();
dogs.Add(banan);
dogs.Add(watson);
dogs.Add(unnamed);
dogs.Add(unknown);
*/
var dogs = new List<Dog> { banan, watson, unnamed, unknown };
----

Ez a megoldás szintaktikailag és működésében is nagyon hasonló az objektum inicializálóhoz: kizárólag akkor kapjuk meg a `dogs` referenciát, ha a lista konstruktora lefutott, és minden elemet hozzá tudtunk adni a kollekcióhoz. Ha az alapértelmezett konstruktort használjuk, itt sem szükséges megadnunk a hívást jelző zárójeleket. A háttérben a kollekció `Add` metódusa hívódik meg az elemek hozzáadására, tehát ez alapvetően megegyezik az alábbival:

[source,csharp]
----
var _dogs = new List<Dog>();
_dogs.Add(banan);
_dogs.Add(watson);
_dogs.Add(unnamed);
_dogs.Add(unknown);
var dogs = _dogs;
----

NOTE:  Elég, ha a snippet fájlból bemutatjuk, nem kell beírni

TIP:  Kivétel esetén sikertelen lesz értékadás.

== Bővítő metódusok

A bővítő metódusok (extension method) révén bármilyen típust -- látszólag -- kiegészíthetünk tetszőleges, további metódusokkal.

Tegyük fel, hogy hiányolunk egy metódust a standard `string` típusról. Szeretnénk, hogy például konzolra történő listázáskor egy paraméterezhető karakterhosszúságú szöveggé vágná le a bemenetet vagy az adott hosszúságúra töltené ki szóközökkel. Ezt a feladatot megoldhatnánk például az alábbi módon: vegyünk fel egy *Extensions* nevű mappát a projekt gyökerében, ebben pedig egy `StringExtensions` osztályt egy ugyanilyen nevű fájlba:

[source,csharp]
----
public static class StringExtensions
{
    public static string TrimPad(string text, int length)
    {
        if ((text?.Length ?? 0) == 0)
            return new string(' ', length);
        if (text.Length <= length)
            return text + new string(' ', length - text.Length);
        return text.Substring(0, length);
    }
}
----

A `??` operátor (null coalescing operátor) a kifejezés bal oldalán álló értéket adja vissza, ha az nem `null`, különben a jobb oldalán álló értéket (tehát kiolvashatjuk „különben, ha `null``”-ként is).

Érdekességképp megvizsgálhatjuk az „egysoros” megoldást, kitérve ennek egyértelmű hátrányaira és előnyére:

[source,csharp]
----
public static string TrimPad(string text, int length) =>
    ((text?.Length ?? 0) == 0)
        ? new string(' ', length)
        : (text.Length <= length)
            ? text + new string(' ', length - text.Length)
            : text.Substring(0, length);
----

TIP:  Elég, ha a snippet fájlból bemutatjuk, nem kell beírni

Teszteljük is le, a `Main` metódusunk elején:

[source,csharp]
----
for (var i = 0; i < 26; i++)
    Console.WriteLine(StringExtensions.TrimPad(new string((char)('a' + i), i), 20));
----

Mivel a statikus osztályunk más névtérben van, használjuk a névteret a *Program.cs* fájl tetején:

[source,csharp]
----
using HelloCSharp2.Extensions;
----

Szebb volna, ha magán a `string`-en tudnánk használni ezt a metódust. Tegyük ki a `this` módosítószót a `TrimPad` metódus szignatúrájába:

[source,csharp]
----
public static string TrimPad(this string text, int length)
----

Ezután a bővítő metódust az alábbi módon is tudjuk használni:

[source,csharp]
----
Console.WriteLine(new string((char)('a' + i), i).TrimPad(20));
----

Ez a megoldás ekvivalens a korábban használttal, szintén csak egy szintaktikai édesítőszerről van szó.

TIP:  A bővítő metódusnak statikus osztályban kell szerepelnie, a metódusnak statikusnak kell lennie, és a szükséges névteret az aktuális fájlban használnunk kell a `using` kulcsszóval.
Amikor statikus osztályban állapotmentes, statikus metódust hozunk létre, amely a bemeneti paramétereken dolgozik, érdemes lehet azokat bővítő metódusként kezelni és az első paraméter elé kitenni a `this` módosítószót, így rövidítve a megírandó kód hosszát.

Ha a `Dog` osztályban átírjuk a `ToString` metódusunkat, kicsit szebbé tehetjük az outputot:

[source,csharp]
----
public override string ToString() =>
    $"{Name.TrimPad(10)} ({Age.ToString().TrimPad(2)} | " +
    $"{AgeInDogYears.ToString().TrimPad(3)})" +
    $"[ID: {Id.ToString().TrimPad(8)}]";
----

Mivel a használni kívánt bővítő metódusunk más névtérben van, ezért `using`-oljuk a névteret a fájl elején (_Ctrl+._):

Még egy kicsit szépíthetünk a helyzeten, ha a metódus típusparamétert is vár. Ekkor minden objektumra használható lesz a bővítő metódus, nem szükséges `ToString()`-et hívni a nem `string` típusú elemeken:

[source,csharp]
----
public static string TrimPad<T> (this T obj, int length)
            => TrimPad(obj.ToString(), length);
----

Ez az új metódus az eredeti _overload_-ja: a `string`-et váró függvény fog meghívódni `string`-ek esetén, minden más esetben a másik implementáció.

TIP:  Mivel minden objektumra működik, ezért fontoljuk meg, mielőtt ilyen általános függvényt írunk, különben nagyon hosszú lesz minden alkalommal az _IntelliSense_ legördülője.

A `Dog` osztályban egyszerűsíthetjük a `ToString` implementációt, kivehetjük a property értékek lekérdezése utáni `ToString` hívásokat:

[source,csharp]
----
public override string ToString() =>
    $"{Name.TrimPad(10)} ({Age.TrimPad(2)} | " +
    $"{AgeInDogYears.TrimPad(3)})" +
    $"[ID: {Id.TrimPad(8)}]";
----

A bővítő metódusokat kiegészítésképpen használhatjuk _collection initializer_-ek bővítésére is. Próbáljunk meg a felsorolt `Dog` elemek közé beszúrni egy `string`-et, nézzük meg, mi történik!

A fordító a nem megfelelő szignatúrájú Add metódus hiányára panaszkodik. Javítsunk ezen! Készítsünk egy olyan bővítő metódust, amely megengedi, hogy `string`-et adjunk a `Dog` kollekcióhoz!

Az *Extensions/DogCollectionExtensions.cs* fájlban vegyük fel az alábbi osztályt:

[source,csharp]
----
public static class DogCollectionExtensions
{
    public static void Add(this ICollection<Dog> source,
                            string name,
                            DateTime? dateOfBirth = null) =>
                source.Add(new Dog
                            {
                                Name = name,
                                DateOfBirth = dateOfBirth
                            });
}
----

TIP:  Az expression bodied method szintaxist érdemes áthívás jellegű esetekben használni (esetünkben ez például egy másik szintaxis invokációját jelenti), azaz amikor a jobb oldali kifejezést közvetlenül vissza is akarjuk adni a hívónak. Egy `void` visszatéréssel rendelkező metódus esetén a típus (hiánya) nem okoz gondot, illetve a jobb oldali visszatérési értéket elrejthetjük, ha a metódusunk `void` visszatérésű.

TIP:  Az utolsó paraméter ún. opcionális paraméter alapértelmezett értékkel. Ezt a paramétert nem szükséges megadnunk a függvény hívásakor, ekkor annak a változónak az értéke a megadott alapértelmezett értéket veszi fel.

Ez a hívás egyszerűen áthív a valódi `Add` metódusba, ami `Dog` típusú elemet vár. Próbáljuk ki a hívást:

[source,csharp]
----
var dogs = new List<Dog> { banan, watson, unnamed, unknown, "Mázli" };
----

Láthatjuk, hogy nem kapunk fordítási hibát, és Mázli kutya is a kollekció része lesz. A többparaméteres hívást is szemléltethetjük, ehhez az egy Add függvényhíváshoz tartozó paramétereket kapcsoszárójelek között soroljuk fel:

[source,csharp]
----
var dogs = new List<Dog> {
    banan,
    watson,
    unnamed,
    unknown,
    "Mázli",
    { "Puffancs", new DateTime(2010, 2, 1) }
};
----

== Index inicializálók

A collection initializer analógiájára jött létre az _index initializer_ nyelvi elem, ami a korábbihoz hasonlóan sorban hív meg egy operátort, hogy már inicializált objektumot kapjunk vissza. A különbség egyrészt a szintaxis, másrészt az ilyenkor meghívott metódus, ami az index operátor. Emlékeztethetjük a hallgatókat, hogy saját típusainkban lehetőségünk van definiálni és felüldefiniálni operátorokat, mint pl. +, -, indexelés, implicit cast, explicit cast, stb. Ilyenkor nem szükséges megvalósítanunk az `IEnumerable` interfészt, egyszerűen csak egy elérhető, beállítható indexer tulajdonságra van szükségünk.

Tegyük fel, hogy egy kutyához bármilyen a domain modellünkbe nem illeszkedő információ kerülhet, amire általános struktúrát szeretnénk. Vegyünk fel a `Dog` osztályba egy `string-object` szótárat, amiben bármilyen további információt tárolhatunk! Ezen felül állítsuk be a `Dog` indexerét, hogy az a `Metadata` indexelését végezze:

[source,csharp]
----
public class Dog
{
    //...
    public Dictionary<string, object>  Metadata { get; }
                    = new Dictionary<string, object>();

    public object this[string key]
    {
        get { return Metadata[key]; }
        set { Metadata[key] = value; }
    }
}
----

Az objektum inicializáló és az index inicializáló vegyíthető, így az alábbi módon tudunk felvenni további tulajdonságokat a kutyákhoz:

[source,csharp]
----
var pimpedli = new Dog()
{
    Name = "Pimpedli",
    DateOfBirth = new DateTime(2006, 06, 10),
    ["Chip azonosító"] = "123125AJ"
};
----

Mivel indexelni általában kollekciókat szokás (tömb, lista, szótár), ezért ezekben az esetekben igen jó eszköz lehet az index inicializáló. Cseréljük le a listánkat az alábbi szótárra:

[source,csharp]
----
var dogs = new Dictionary<string, Dog>
{
    ["banan"] = banan,
    ["watson"] = watson,
    ["unnamed"] = unnamed,
    ["unknown"] = unknown
};

foreach (var dog in dogs)
    Console.WriteLine($"{dog.Key.TrimPad(10)} - {dog.Value}");
----

Elsőre jó ötletnek tűnhet kiváltani a szövegliterálokat a `Name` property használatával.

[source,csharp]
----
var dogs = new Dictionary<string, Dog>
{
    [banan.Name] = banan,
    [watson.Name = watson,
    [unnamed.Name] = unnamed,
    [unknown.Name] = unknown
};
//ArgumentNullException!
----

Ez azonban kivételt okoz, amikor a kutya neve nincs kitöltve, azaz `null` értékű. Esetünkben elég lenne az adott változó neve szövegként. Erre jó a `nameof` operátor.

[source,csharp]
----
var dogs = new Dictionary<string, Dog>
{
    [nameof(banan)] = banan,
    [nameof(watson)] = watson,
    [nameof(unnamed)] = unnamed,
    [nameof(unknown)] = unknown
};
----

Ez a változat már nem fog kivételt okozni.

Mivel az index- és a collection initializer nem vegyíthető, ezért a kettő közül most választanunk kell. Ilyenkor az `Add` metódus változatait nem használhatjuk.

A `Dictionary<TKey, TValue>` rendelkezik egy `Add` metódussal, amelyik egy `TKey` és egy `TValue` típusú értéket vár, ezért használhatjuk a collection initializert is:

[source,csharp]
----
var dogs = new Dictionary<string, Dog>
{
    { "banan", banan },
    { "pimpedli", pimpedli },
    { "unnamed", unnamed },
    { "unknown", unknown },
    { "unknown", unknown }
};
----
