= Felhasználókezelés Azure B2C használatával

== Kiegészítő anyagok, segédeszközök, előfeltételek

* Azure előfizetés szükséges (ingyenes is megfelelő), a lehetőségekről https://www.aut.bme.hu/Course/felho#azuresub[bővebben itt]

== Bevezetés

A felhasználókezelés az utóbbi években igen összetetté vált. Egy modern megoldásnak ma már része az alábbiak közül számos képesség:

* email ellenőrzés regisztrációkor, email megerősítés bizonyos műveleteknél
* többfaktoros beléptetés (pl. mobil eszközzel)
* elfelejtett jelszó kezelése
* felhasználók letiltása
* botok kiszűrése (CAPTCHA)
* single sign-on
 ** egy szervezeten belül vagy
 ** külső identitások támogatása (Google, Facebook, Microsoft fiók)
* profil megtekintése, szerkesztése, törlése
 ** külső identitások kapcsolása, leválasztása
 ** GDPR funkciók: személyhez kapcsolódó adatok önkiszolgáló megtekintése, törlése
* adminisztrációs felület
 ** felhasználók megtekintése, letiltása, új jelszó generálási folyamat indítása

Ez a bonyolódás maga után vonta a kapcsolódó technológiák bonyolódását is. Megjelentek  különböző típusú alkalmazáskörnyezetekre (webes, mobil) különböző szabványos authorizációs folyamatok (https://medium.com/@darutk/diagrams-and-movies-of-all-the-oauth-2-0-flows-194f3c3ade85[OAuth flow-k]) és ezekre épülő kiterjesztések, például az https://openid.net/developers/specs/[OpenID].

{empty}.NET környezetben elérhetőek ezen szabványok implementációi, azonban a magasabb szintű támogatás (pl. Visual Studio projektsablonok, generátorok, varázslók) többnyire az egyszerűbb esetekre, a webes alkalmazásokra, azon belül is a szerver oldali rendereléssel dolgozókra (ASP.NET Core MVC) korlátozódott. Az MVC-s Identity template _süti alapú_ authentikációt használ. Szélesebb körben (pl. mobilkliensek) használhatóak a _token alapú_ (pl. JWT token), OAuth/OpenID megoldások, így a továbbiakban csak erre koncentrálunk.

=== Token alapú felhasználókezelés

Tipikus az ilyen rendszerekben, hogy egy kitüntetett entitás az ún. *identity provider/authorization server* tokeneket állít elő, amelyeket az alkalmazás, ahová a kliensalkalmazás előtt ülő felhasználó be akar lépni (_relying party_, _resource server_) ellenőriz. A felhasználó a kliensprogramján keresztül az azonosítás alatt kizárólag az _identity provider_-rel kommunikál, neki adja meg a jelszavát például. Így tehát alapvetően három szereplő van: a kliensprogram (egy böngésző is lehet), a _relying party_ (RP/RS) és az _identity provider_ (IDP/AS). Egy IDP több RP-t is kiszolgálhat, így sokszor az IDP telepítési szempontból is egy külön komponens.

Ezen szabványokat implementálták a fejlettebb platformokra, így ASP.NET Core-ra is, tipikusan az alábbi technológiákat/komponenseket alkalmazhatjuk:

* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity[ASP.NET Core Identity] (a Shared Framework része)
** adatelérési és üzleti logikai réteg a felhasználói adatok kezelésére
** JWT Bearer token middleware, ASP.NET Core authorizációs rendszer - RP feladatokhoz
* https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.UI[Identity UI] - az Identity Core-hoz tartozó felület (ASP.NET Core Razor alapú)
* https://duendesoftware.com/[Duende IdentityServer] (korábban IdentityServer) - 4-es verzióig nyílt forráskódú IDP, széleskörű támogatás tokenkezelési, IDP feladatokhoz. 5-ös verziótól kezdve licenszköteles, bár sok esetben igényelhető ingyenes licensz.
* https://github.com/skoruba/Duende.IdentityServer.Admin[Duende IdentityServer Admin UI] - adminisztrációs felület a Duende IdentityServer-hez
* https://docs.microsoft.com/en-us/azure/active-directory/develop/[Microsoft identity platform] - komponensek Microsoft IDP szolgáltatások (Azure AD, Azure AD B2C - lásd lentebb) igénybe vételéhez szerver- és kliensoldalhoz is. Nem önálló IDP megoldás, önmagában nem használható. Az újgenerációs komponenskönyvtárak MSAL néven érhetőek el különböző platformokra: MSAL.NET .NET-hez, MSAL.js JavaScript-hez, stb.

Látható, hogy maga a Microsoft alapvetően csak a tokenek ellenőrzésére (RP feladat) biztosít magasszintű API-t, komponenst ASP.NET Core-ban, tokenek előállítására nem (IDP feladat). Ez utóbbira lehet jó a _Duende IdentityServer_, de ezen felül egyéb alternatívák is https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community[elérhetők].

Jelenleg (2022. tavasz) az ASP.NET Core projektsablonok a következő IDP technikákat használják:

* ASP.NET Core Web App: semmilyet, mert nem token, hanem süti alapú!
* ASP.NET Core Web API: Microsoft identity platform vagy on-premise Active Directory (ez utóbbi lokális hálózaton működik)
* ASP.NET Core with Angular/React.js: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization[Duende IdentityServer]

Az IDP feladatok elég jól leválaszthatók, így megjelentek azok a szolgáltatások, melyek segítségével gyakorlatilag minden IDP feladatot kiszervezhetünk, beleértve a fentebb felsorolt képességeket is. Ezek az ún. _IDentity as a Service (IDaaS)_ vagy _Authentication as a Service_ szolgáltatások. Néhány példa: https://www.okta.com/[_Okta_], https://auth0.com/[_Auth0_] (2021. tavaszán felvásárolta az Okta), _Azure AD B2C_. Ezek alapvetően nem ingyenes szolgáltatások, bár többnyire bizonyos méret/felhasználószám/tokenmennyiség alatt ingyenesen használhatóak. További lehetőség saját üzemeltetésű, de külön telepíthető, kész IDP telepítése. Ez lehet akár nem .NET-es is, hiszen a kommunikáció szabványokra (OAuth, OpenID Connect) épül - ilyenre egy példa a https://www.keycloak.org/[keycloak]. Ezen gyakorlat során az Azure AD B2C szolgáltatást fogjuk használni, amivel az utolsó kivételével *minden fenti komponenst kiváltunk*.

A megvalósítandó rendszerben:

* az Azure B2C lesz az IDP/Authorization Server
* egy generált ASP.NET Core alkalmazás lesz a RP/Resource Server
 ** az alkalmazásból publikált webes API-t csak autentikált felhasználók érhetik el
 ** Microsoft identity platform komponenseket (MSAL.NET) használunk a B2C specifikus feladatok megoldásához. Konkrétan a https://github.com/AzureAD/microsoft-identity-web[Microsoft.Identity.Web] csomag biztosítja az ASP.NET Core általános felhasználókezelés alrendszerének és az https://github.com/AzureAD/microsoft-authentication-library-for-dotnet[MSAL.NET]-nek az https://github.com/AzureAD/microsoft-identity-web/wiki/Microsoft-Identity-Web-basics#high-level-architecture[összehangolását].
* egy szintén generált Blazor WebAssembly alkalmazást lesz a kliens, mely
 ** a felhasználókezelési folyamatok végrehajtásához a B2C által kiszolgált felületekre irányít át
 ** az ASP.NET Core alkalmazásunk API-ját hívja
 ** a https://www.nuget.org/packages/Microsoft.Authentication.WebAssembly.Msal[Microsoft.Authentication.WebAssembly.Msal] csomagot használunk a B2C specifikus feladatok megoldásához. Ez a csomag egy .NET-es JavaScript interop réteget ad az https://github.com/AzureAD/microsoft-authentication-library-for-js[MSAL.js] fölé.
* az OAuth https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#protocol-diagram[*Authorization Code Flow*] folyamatot fogjuk követni. A PKCE-vel (https://datatracker.ietf.org/doc/html/rfc7636[Proof Key for Code Exchange]) kiegészített változata az ajánlott flow szinte mindenfajta kliens (vastagkliens, web, mobil) számára. SPA-k (angular, react, Blazor WebAssembly, stb.) számára gyakorlatilag csak ez számít biztonságosnak.

TIP: Az Azure B2C-ben az első 50000 aktív felhasználó kiszolgálása https://azure.microsoft.com/en-us/pricing/details/active-directory-b2c/[ingyenes] minden hónapban.

== Hosted WebAssembly alkalmazásból védett API hívása

Kövessük a hivatalos https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-6.0[Microsoft útmutatót], itt csak az eltéréseket emeljük ki. A következő alcímek megfelelnek az útmutató alcímeinek.

=== Előkészítés: Azure B2C Tenant létrehozása

TIP: Érdemes https://docs.microsoft.com/en-us/azure/azure-portal/set-preferences#change-language-and-regional-settings[angolra állítani] az Azure portál nyelvét, értelmesebb hibaüzeneteket kaphatunk.

WARNING: Az erőforrások létrehozása, kezelése a portálról indítva is API hívásokkal történik. Számos ilyen API van, ezeket _resource provider_-eknek hívjuk. A B2C-hez kapcsolódó _resource provider_ gyakran le van tiltva alapértelmezésben. Ilyenkor a létrehozás hibára fut (_The subscription is not registered to use namespace 'Microsoft.AzureActiveDirectory'_). A javításhoz https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider-1[engedélyezzük (regisztráljuk)] a hibaüzenetben jelzett _providert_.

=== A RP regisztrálása Azure B2C-be

Bár még nincs meg az RP alkalmazásunkból semmi, a regisztrációját elkészítjük. 

=== A kliensalkalmazás regisztrálása Azure B2C-be

Bár még nincs meg a kliensalkalmazásunkból sem semmi, a regisztrációját elkészítjük. Ha szeretnénk a B2C tesztfelületéről tesztelni a felhasználókezeléses felületeket, akkor a szakasz végén az _implicit grant flowt_ is https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-spa#enable-the-implicit-flow[engedélyezzük] az alkalmazás **Authentication** menüpontjában és ugyanitt redirect URL-ként a `https://jwt.ms` címet is vegyük fel.

TIP: A https://jwt.ms[jwt.ms] oldalon dekódolhatjuk a JWT tokenjeinket, de az authorization code flow-t redirect URI-ként nem támogatja.

WARNING: Az https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#protocol-diagram[implicit grant flowt] csak azért engedélyezzük, hogy a _jwt.ms_ oldalon történő tesztelés majd működjön (lásd a következő szakasz), de ez már egy elavult folyamat (ezért nincs is alapból engedélyezve) - csak tesztelési célból kapcsoljuk be.

==== User flow / policy létrehozása, kipróbálása

Egy kombinált regisztrációs-belépési folyamatot (_Sign up and sign in_) hozunk létre.

Ezeket az extra adatokat gyűjtsük be a felhasználókról (Collect attribute):

* keresztnév (Given name)
* vezetéknév (Surname)
* felhasználónév (Display Name)

Ezeket az extra adatokat kódoltassuk bele a tokenbe (Return claim):

* keresztnév (Given name)
* vezetéknév (Surname)
* email címek (Email addresses)
* felhasználónév (Display Name)

Ha korábban engedélyeztük az implicit flow-t, próbáljuk ki az új folyamatot a https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow[linkelt útmutató] alapján (_Test the user flow_ alcím). Válasszuk ki a kliensalkalmazást tesztelendő alkalmazásként. Regisztráljunk és lépjünk be. Ellenőrizzük a https://jwt.ms[JWT dekóder oldalon] a tokenbe kerülő claim-eket.

Derítsük fel a B2C _Users_ oldalát. Ez egy adminisztratív felület, a regisztrált felhasználók adatait látjuk, módosíthatjuk, valamint a jelszavukat is visszaállíthatjuk.

WARNING: A Blazor WebAssembly az MSAL JavaScript verzióját használja (MSAL.js), azonban ennek https://github.com/dotnet/aspnetcore/issues/38122[sem minden funkcióját teszi elérhetővé]. Emiatt több B2C-s beépített user flow https://github.com/dotnet/aspnetcore/issues/27549[sem használható] (egyszerűen) Blazor WebAssembly-ből (például jelszóvisszaállítás, profilszerkesztés).

=== Kliens és szerver alkalmazás generálása

Ebben a fázisban a beépített .NET sablonok segítségével egy alapszinten működő, konfigurált felhasználókezelést-hozzáférésszabályozást kapunk mind szerver-, mind kliensoldalon.

TIP: Az Azure B2C kommunikáció szabványokra épül, így szinte bármilyen (nem csak .NET alapú) klienstechnológiát használhatunk. Számos https://docs.microsoft.com/en-us/azure/active-directory-b2c/code-samples[mintaprojekt] elérhető különböző technológiákhoz. Az MSAL komponens is számos fejlesztői platformra https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview[elérhető]. A legtöbb mintaprojektet próba B2C tenanttal is https://github.com/Azure-Samples/active-directory-b2c-dotnet-desktop#using-the-demo-environment[ki lehet próbálni], ilyenkor nem is kell Azure előfizetés.

=== Szerveralkalmazás felderítése

A szakasz végén ki is próbálhatjuk, hogy a `/WeatherForecast` címre hívva böngészőből 401-es hibát kapunk, míg ha az `Authorize`, `RequiredScope` attribútumokat ideiglenesen levesszük a WeatherForecastController osztályról, akkor visszakapjuk az adatokat.

=== Kliensalkalmazás felderítése

A szakasz végén próbáljuk ki a bal oldali **Fetch Data** és/vagy a jobb felső sarokban a **Log in/Logout** menüpontos segítségével a főbb folyamatokat: regisztráció, belépés, kilépés. Próbáljuk ki, hogy belépés után megjelennek-e az időjárásadatok.

=== Felhasználói adatok megfigyelése kliensoldalon

Az https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-6.0#inspect-the-user[útmutatót] követve Blazor projekt **Pages** mappájába vegyünk fel egy új Razor komponenst (_Razor component_, nem _Razor page_!) **User.cshtml** névvel. Ebbe másoljuk bele a https://github.com/dotnet/aspnetcore/blob/v6.0.4/src/Components/WebAssembly/testassets/Wasm.Authentication.Client/Pages/User.razor[mintakomponens kódját]. Ezután a `/User` címre navigálva az access token adatait láthatjuk.

== Egyéb Azure B2C funkciók

=== Felhasználó/csoport szintű hozzáférés-szabályozás

A felhasználókat tipikusan csoportokba soroljuk és az egyes csoportokra nézve osztjuk ki a hozzáférést. Az Azure AD B2C nem rendelkezik csoportadminisztrációs képességgel, azonban a kapcsolódó Azure AD-ba fel lehetne venni csoportokat, a felhasználók csoportba rendezhetnénk, kivehetnénk stb. Ehhez egyrészt az Azure AD-ban is magas szintű jogok kellenének, másrészt saját https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview[B2C-beli policy-t] (nem ugyanaz, mint az ASP.NET Core authentikációs házirend) kellene implementálni, amivel a tokenelőállítást tudnánk testre szabni, hogy az AD csoporttagság is bekerüljön a tokenbe. Ez elég macerás, még úgy is, hogy van rá https://github.com/azure-ad-b2c/samples/tree/master/policies/groups[hivatalos példaimplementáció], ezért egy sokkal fapadosabb megoldást követünk.

Küldjük le a tokenben a felhasználó B2C-beli azonosítóját. A regisztrációs-belépési folyamat (_User flows_) beállításai között az _Application claims_ menüpontban jelöljük ki az *User's Object ID* claim-et. Mentsünk.

Vegyünk fel egy új házirendet a szerveroldal legfelső szintű kódjába úgy, hogy azt csak konkrét B2C-beli azonosítóval rendelkező felhasználók teljesítsék. A már regisztrált felhasználók adatait, többek között az Object ID-ját is megnézhetjük a B2C _Users_ nevű oldalán, a kívánt felhasználót kiválasztva. Válogassunk össze pár olyan *Object ID*-t, aminek a felhasználójának ismerjük a belépési adatait.

[source,csharp]
----
builder.Services.AddAuthorization(options=>
    options.AddPolicy("Admin", policy =>
        policy.RequireClaim(
            "http://schemas.microsoft.com/identity/claims/objectidentifier"
            //Vegyünk fel egy-két Object ID-t a regisztrált felhasználók közül
            , "00000000-0000-0000-0000-000000000000"
            , "00000000-0000-0000-0000-000000000000" ))
    
);
----

TIP: Egyértelműen elegánsabb lenne, ha ez a csoporttagság konfigurációból vagy az Azure B2C csoportkezelő funkciójából származna.

A fenti házirend szerint az teljesíti az `Admin` házirendet, akinek az *Object ID*-ja a felsoroltak közt van - azaz a megadott értékek közül elég legalább egynek megfelelni a házirend teljesítéséhez.

Követeljük meg az új házirendet a kontrolleren.

[source,csharp]
----
[Authorize("Admin")] //házirend megadása
----

TIP: Műveleteken is elhelyezhetünk `Authorize` attribútumot. Minden elemre (kontroller, művelet) nézve a lefutásának feltétele, hogy az összes szülőelemen megkövetelt minden házirend teljesüljön.

A Blazor alkalmazásban lépjünk ki, majd be, végül próbáljuk ki az API hívást előbb egy az új házirendben elvárt *Object ID*-val rendelkező felhasználóval, majd egy egyéb felhasználóval (például egy újonnan regisztrálttal). Utóbbi esetben nem szabad eredményt kapnunk, de a szerveralkalmazás konzolján naplózódik a kérés elutasítása.

TIP: Az *Object ID* a tokenbe `oid` kulccsal kerül be és a felhasználót azonosítja. Hasonló, bár nem teljesen azonos a `sub` kulcs, ami alkalmazás-felhasználó kombinációra https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims[egyedi].

=== Elfelejtett jelszó funkció

Ezt egyszerűen csak https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended[be kell kattintani] a regisztrációs folyamat beállításai között. Próbáljuk ki a bejelentkező felületen a _Forgot your password?_ link aktiválásával.

=== Social login

A B2C számos külső identitásszolgáltatóval (IDP) képes együttműködni, például Google, Twitter, GitHub, Facebook, stb. És persze Microsoft.

Az integrációhoz szükségünk lesz egy felhasználói/fejlesztői fiókra a kiválasztott identitásszolgáltatónál. Az integrációhoz kövessük a hivatalos útmutatót, például a https://docs.microsoft.com/hu-hu/azure/active-directory-b2c/active-directory-b2c-setup-msa-app[Microsoft Account-ra (MSA) vonatkozót].

WARNING: Az MSA integráció nehézsége, hogy első lépésben egy ún. https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-microsoft-account?pivots=b2c-user-flow#create-a-microsoft-account-application[Microsoft account application-t] kell létrehozni, de ehhez a B2C-s tenant nem jó, egyetemi, céges tenantoknál pedig körülményes, mert a szükséges Azure AD felületeket gyakran letiltják. Megoldás lehet, ha a privát MS fiókkal (@hotmail.com, @outlook.com) lépünk be az Azure portálra és így a saját tenantunkban hozzuk létre az MS account application-t.

Az integrációt követően a folyamatainkban felhasználhatjuk a külső IDP-t, ehhez a folyamat beállításainál lévő _Identity providers_ menüpontban válasszuk ki az adott folyamatban engedélyezni kívánt IDP-ket. Ezután a regisztrációs, belépés felületeken megjelennek az engedélyezett IDP-khez tartozó felület(elem)ek.

A kliensalkalmazás és a RP módosítására nincs szükség.

== Védett API hívása Postmanből

Hozzunk létre https://learning.postman.com/docs/sending-requests/requests/#creating-requests[új HTTP kérést (HTTP Request)] Postman-ben. A kérés legyen **GET** típusú, a cím legyen egy azonosítást igénylő (védett) művelet címe. A generált projektben ilyen a `WeatherForecastController.Get()` művelete, adjuk meg ennek a HTTPS címét, pl.: https://localhost:5001/WeatherForecast

Próbáljuk meghívni elküldeni a kérést, 401-es hibakódot kell kapjunk a válaszban sikertelen azonosítás miatt.

Vegyük fel az Azure portálon a kliensalkalmazáshoz a _\https://oauth.pstmn.io/v1/callback_ címet redirect URI-ként.

WARNING: Mivel az alkalmazásunk HTTPS címét használjuk, és ez a cím általában csak fejlesztői tanúsítvánnyal rendelkezik, szükség lehet a tanúsítványellenőrzés https://learning.postman.com/docs/sending-requests/certificates/#troubleshooting-certificate-errors[kikapcsolására] Postman-ben.

A Postman kérés _Authorization_ fülén a bal oldalt töltsük ki az alábbiak szerint:

- Type: _OAuth 2.0_
- Add Authorization data to: _Request Headers_

A jobb oldalt pedig az alábbiak szerint:

* _Current token_ rész
** Access Token: ez majd a sikeres belépés után töltődik ki
** Header Prefix: _Bearer_
* _Configure New Token - Configuration Options_ rész
** Token name: mi választjuk (pl. b2c), ezzel azonosítjuk a tokent a Postmanen belül
** Grant Type: _Authorization Code (With PKCE)_
** Callback URL: _\https://oauth.pstmn.io/v1/callback_, illetve az _Authorize using browser_ ne legyen bepipálva. Ilyenkor a Postman saját böngészőablakot fog feldobni. Ha bepipáljuk, akkor az alapértelmezett böngészőben fog elindulni a belépési folyamat.
** Auth URL: Az Azure portálon a kliensalkalmazás _Overview_ menüpontjában felül nyomjuk meg az _Endpoints_ gombot. Jobb oldalon megjelennek a B2C IDP URL-jei. Ezek közül a _Azure AD B2C OAuth 2.0 authorization endpoint (v2)_ URL kell. Az URL-ben a `<policy-name>` helyőrzőt le kell cserélnünk a belépési folyamat nevére. Példa: _\https://myb2c.b2clogin.com/myb2c.onmicrosoft.com/b2c_1_susi/oauth2/v2.0/authorize_
** Access Token URL: ugyanúgy szerezzük meg, mint az Auth URL-t, csak itt a _Azure AD B2C OAuth 2.0 token endpoint (v2)_ URL kell. A helyőrzőt itt is cserélni kell. Példa: _\https://myb2c.b2clogin.com/myb2c.onmicrosoft.com/b2c_1_sg/oauth2/v2.0/token_
** Client ID: a kliensalkalmazás Client ID-ja (amit a projektgeneráláskor _--client-id_-ként is megadtunk)
** Client Secret: maradjon üres
** Code Challenge Method: _SHA-256_
** Code Verifier: maradjon üres
** Scope: az általunk felvett scope **teljes scope URL-je** (pl. _\https://myb2c.onmicrosoft.com/00000000-0000-0000-0000-000000000000/API.Access_). Az Azure portálon a kliensalkalmazás _API permission_ menüpontjában kattintsunk rá a scope nevére. Jobb oldalon megjelenik az URL.
** State: maradjon üres
** Client Authentication: maradjon az előre beállított

Alul kérjük el a tokent a _Get New Access Token_ gombbal. Egy böngészőablak fog megnyílni, az Azure B2C belépési felülettel. Lépjünk be egy olyan felhasználóval, ami jogosult a védett művelet meghívására. Miután beléptünk, a Postman ki tudja olvasni a tokent, ami bekerül a _Current token_ részre. Ezután küldjük újra a kérést. Most már sikerülnie kell, vissza kell kapnunk az időjárásadatokat.

